var enDictNumber = {
  1: '1st',
  2: '2nd',
  3: '3rd',
  4: '4th',
  5: '5th'
}
var isLong = {
  'zh-CN': 4,
  'zh-TW': 4,
  'ko-KR': 4,
  'en-US': 8
}
var langs = {
  'zh-CN': {
    'BpHelper': '背锅助手',
    'from': '来自',
    'left': '我方',
    'right': '敌方',
    'ban': '禁用',
    'pick': '选择',
    'first': '先选',
    'move': '手',
    'hero': '英雄',
    'reason': '理由',
    'player': '玩家',
    'records': '场次',
    'current': '当前',
    'points': '分',
    'winPercent': '胜率',
    'Hero stars': '英雄熟练度',
    'Map': '地图',
	'No advices': '没有英雄推荐',
    'BP finished': '已完成',
    'BP finished tips': '谨记：合作是胜利的前提',
    'Hero name not exist': '英雄不存在',
    'Waiting for BP': '等待进入 禁选环节',
    'BP tips title': '手动模式说明',
    'Please select map and team first pick': '进入禁选环节后请选择地图及先选方',
    'BP tips 1': '1.输入英雄的拼音缩写可以快速搜索英雄或地图（如aess-阿尔萨斯）',
    'BP tips 2': '2.使用快捷键 Ctrl+Shift+B 隐藏/显示背锅助手窗口',
    'Copy advice': '复制给队友',
    'Copied': '已复制',
    'recommend': '推荐',
    'Average MMR': '平均 MMR',
    'Unselected': '未选择',
    'Ready': '准备就绪',
    'Finished': '已完成',
    'Popular Talent': '热门天赋',
    'QuickMatch': '快速匹配',
    'HeroLeague': '英雄联赛',
    'TeamLeague': '团队联赛',
    'UnrankedDraft': '非排名模式',
    'Chose Mode': '选择模式',
    'Source by hotslogs.com': '数据来源 hotslogs.com',
    'Loading': '...',
    'Overtime': '超时',
    'No data': '无数据',
    'Click button on the top-right to close': '可点击右上角按钮关闭',
    ' seconds to close': ' 秒后关闭',
    '(Click here to stop)': '（点此阻止关闭）',
	'Need update': '版本已过期，请重启客户端进行更新',
    'Warrior': '战斗型',
    'Assassin': '刺杀型',
    'Support': '辅助型',
    'Specialist': '专业型',
    'Warcraft': '魔兽',
    'StarCraft': '星际争霸',
    'Diablo': '暗黑破坏神',
    'Retro': '复古',
    'Overwatch': '守望先锋',
	'Tank': '坦克',
	'Bruiser': '斗士',
	'Ambusher': '近刺',
	'Magician': '法师',
	'Shooter': '射手',
	'RangedMixed': '远程混合',
	'RangedDisturbance': '远程扰乱',
	'Healer': '治疗',
	'Guardian': '守护',
    'mmrLeft': '左',
    'mmrRight': '右',
    'mmrReportRate': '胜率情报：',
    'mmrReport': '情报：',
    'mmrLeftHigher': '左方平均MMR高于右方',
	'mmrLeftSignificantlyHigher': '左方平均MMR远高于右方',
	'mmrRightHigher': '左方平均MMR低于右方',
	'mmrRightSignificantlyHigher': '左方平均MMR远低于右方',
	'mmrRightEqual': '本场平均MMR双方接近',
	'Hots Patch Wrong': '暂不能识别此游戏版本英雄'
  },
  'zh-TW': {
    'BpHelper': '背鍋助手',
    'from': '來自',
    'left': '我方',
    'right': '敵方',
    'ban': '禁用',
    'pick': '選擇',
    'first': '先選',
    'move': '手',
    'hero': '英雄',
    'reason': '理由',
    'player': '玩家',
    'records': '場次',
    'current': '當前',
    'points': '分',
    'winPercent': '勝率',
    'Hero stars': '英雄熟练度',
    'Map': '地圖',
	'No advices': '沒有英雄推薦',
    'BP finished': '已完成',
    'BP finished tips': '謹記：合作是勝利的前提',
    'Hero name not exist': '英雄不存在',
    'Waiting for BP': '等待進入 禁選環節',
    'BP tips title': '手動模式說明',
    'Please select map and team first pick': '進入禁選環節后請選擇地圖及先選方',
    'BP tips 1': '1.輸入英雄的註音縮寫可以快速搜索英雄或地圖（如ㄇㄈㄌㄣ-瑪法里恩）',
    'BP tips 2': '2.使用快捷鍵 Ctrl+Shift+B 隱藏/顯示背鍋助手窗口',
    'Copy advice': '複製給隊友',
    'Copied': '已複製',
    'recommend': '推薦',
    'Average MMR': '平均 MMR',
    'Unselected': '未選擇',
    'Ready': '準備就緒',
    'Finished': '已完成',
    'Popular Talent': '最熱天賦',
    'QuickMatch': '快速匹配',
    'HeroLeague': '英雄聯賽',
    'TeamLeague': '團隊聯賽',
    'UnrankedDraft': '非排名模式',
    'Chose Mode': '選擇模式',
    'Source by hotslogs.com': '數據来源 hotslogs.com',
    'Loading': '...',
    'Overtime': '超時',
    'No data': '無數據',
    'Click button on the top-right to close': '可點擊右上角按鈕關閉',
    ' seconds to close': ' 秒后關閉',
    '(Click here to stop)': '（點此阻止關閉）',
	'Need update': '版本已過期，請重啓用戶端進行更新',
    'Warrior': '戰士',
    'Assassin': '刺客',
    'Support': '輔助',
    'Specialist': '專家',
    'Warcraft': '魔獸爭霸',
    'StarCraft': '星海爭霸',
    'Diablo': '暗黑破壞神',
    'Retro': '懷舊經典',
    'Overwatch': '鬥陣特攻',
	'Tank': '坦克',
	'Bruiser': '鬥士',
	'Ambusher': '近戰刺客',
	'Magician': '法師',
	'Shooter': '射手',
	'RangedMixed': '遠程混合',
	'RangedDisturbance': '遠程擾亂',
	'Healer': '治療',
	'Guardian': '守護',
    'mmrLeft': '左',
    'mmrRight': '右',
    'mmrReportRate': '勝率情報：',
    'mmrReport': '情報：',
    'mmrLeftHigher': '左方平均MMR高於右方',
	'mmrLeftSignificantlyHigher': '左方平均MMR远高于右方',
	'mmrRightHigher': '左方平均MMR遠高於右方',
	'mmrRightSignificantlyHigher': '左方平均MMR遠低於右方',
	'mmrRightEqual': '本場平均MMR雙方接近',
	'Hots Patch Wrong': '暫不能識別此遊戲版本英雄'
  },
  'ko-KR': {
    'BpHelper': 'BP Hots',
    'from': 'from',
    'left': '왼쪽',
    'right': '오른쪽',
    'ban': '금지',
    'pick': '선택',
    'first': '우선',
    'move': '번',
    'hero': '영웅',
    'reason': '이유',
    'player': '선수',
    'records': '기록',
    'current': '지금',
    'points': '점',
    'winPercent': 'Win Percent',
    'Hero stars': 'Proficiency',
    'Map': 'Map',
	'No advices': 'No result',
    'BP finished': 'BP 완성',
    'BP finished tips': 'Cooperation makes victory.',
    'Hero name not exist': '영웅이름 존재하지 않음',
    'Waiting for BP': '기다리다 시작',
    'BP tips title': 'Manual Mode Tips',
    'Please select map and team first pick': '지도과 BP시작방 입력/선택하세요',
    'BP tips 1': '1. 영우이름 입력후 리스트가 나와서 편하게 선택할 수 이습니다.',
    'BP tips 2': '2. Ctrl+Shift+B누르면 BpHelper를 숨기기/표시하기.',
    'Copy advice': '멤버에게 보내기',
    'Copied': '복사 완성',
    'recommend': '추천',
    'Average MMR': '평균MMR',
    'Unselected': '선택 취소됨',
    'Ready': '준비된',
    'Finished': '이미 끝났다',
    'Popular Talent': '핫 특성',
    'QuickMatch': '빠른 일치',
    'HeroLeague': '영웅 리그',
    'TeamLeague': '팀 리그',
    'UnrankedDraft': '비 순위 초안',
    'Chose Mode': '패션 것',
    'Source by hotslogs.com': '데이터 원본 hotslogs.com',
    'Loading': '...',
    'Overtime': 'OT',
    'No data': 'No data',
    'Click button on the top-right to close': 'Click button on the top-right to close',
    ' seconds to close': ' seconds to close',
    '(Click here to stop)': '(Click here to stop)',
	'Need update': 'Your BpHots client need to be updated',
    'Warrior': '전사',
    'Assassin': '암살자',
    'Support': '지원가',
    'Specialist': '전문가',
    'Warcraft': '워크래프트',
    'StarCraft': '스타크래프트',
    'Diablo': '디아블로',
    'Retro': '고전',
    'Overwatch': '오버워치',
	'Tank': 'Tank',
	'Bruiser': 'Bruiser',
	'Ambusher': 'Ambusher',
	'Magician': 'Magician',
	'Shooter': 'Shooter',
	'RangedMixed': 'RangedMixed',
	'RangedDisturbance': 'RangedDisturbance',
	'Healer': 'Healer',
	'Guardian': 'Guardian',
    'mmrLeft': 'L',
    'mmrRight': 'R',
    'mmrReportRate': 'Win rate report: ',
    'mmrReport': 'Report: ',
    'mmrLeftHigher': 'The average MMR of the left team is higher.',
	'mmrLeftSignificantlyHigher': 'The average MMR of the left team is significantly higher.',
	'mmrRightHigher': 'The average MMR of the right team is higher.',
	'mmrRightSignificantlyHigher': 'The average MMR of the right team is significantly higher.',
	'mmrRightEqual': 'The average MMR of both teams are about the same.',
	'Hots Patch Wrong': 'The version is too old.'
  },
  'en-US': {
    'BpHelper': 'BP Hots',
    'from': 'from',
    'left': 'Blue Team',
    'right': 'Red Team',
    'ban': 'Ban',
    'pick': 'Pick',
    'first': 'first',
    'move': 'Step',
    'hero': 'Hero',
    'reason': 'Reason',
    'player': 'Player',
    'records': 'Records',
    'current': 'Current',
    'points': 'points',
    'winPercent': 'Win Percent',
    'Hero stars': 'Proficiency',
    'Map': 'Map',
	'No advices': 'No result',
    'BP finished': 'Completed',
    'BP finished tips': 'Cooperation makes victory.',
    'Hero name not exist': 'No hero data',
    'Waiting for BP': 'Waiting for start',
    'BP tips title': 'Manual Mode Tips',
    'Please select map and team first pick': 'You can select or input map and team first pick',
    'BP tips 1': '1. Select or input your map and hero in drop-down list.',
    'BP tips 2': '2. Use Ctrl+Shift+B to hide or show BpHelper.',
    'Copy advice': 'Copy to mates',
    'Copied': 'Copied',
    'recommend': 'advice',
    'Average MMR': 'Average MMR',
    'Unselected': 'Unselected',
    'Ready': 'Ready',
    'Finished': 'Finished',
    'Popular Talent': 'PopTalent',
    'QuickMatch': 'Quick Match',
    'HeroLeague': 'Hero League',
    'TeamLeague': 'Team League',
    'UnrankedDraft': 'Unranked Draft',
    'Chose Mode': 'Chose mode',
    'Source by hotslogs.com': 'Source by hotslogs.com',
    'Loading': '...',
    'Overtime': 'OT',
    'No data': 'No data',
    'Click button on the top-right to close': 'Click button on the top-right to close',
    ' seconds to close': ' seconds to close',
    '(Click here to stop)': '(Click here to stop)',
	'Need update': 'Your BpHots client need to be updated',
    'Warrior': 'Warrior',
    'Assassin': 'Assassin',
    'Support': 'Support',
    'Specialist': 'Specialist',
    'Warcraft': 'Warcraft',
    'StarCraft': 'StarCraft',
    'Diablo': 'Diablo',
    'Retro': 'Retro',
    'Overwatch': 'Overwatch',
	'Tank': 'Tank',
	'Bruiser': 'Bruiser',
	'Ambusher': 'Ambusher',
	'Magician': 'Magician',
	'Shooter': 'Shooter',
	'RangedMixed': 'RangedMixed',
	'RangedDisturbance': 'RangedDisturbance',
	'Healer': 'Healer',
	'Guardian': 'Guardian',
    'mmrLeft': 'L',
    'mmrRight': 'R',
    'mmrReportRate': 'Win rate report: ',
    'mmrReport': 'Report: ',
    'mmrLeftHigher': 'The average MMR of the left team is higher.',
	'mmrLeftSignificantlyHigher': 'The average MMR of the left team is significantly higher.',
	'mmrRightHigher': 'The average MMR of the right team is higher.',
	'mmrRightSignificantlyHigher': 'The average MMR of the right team is significantly higher.',
	'mmrRightEqual': 'The average MMR of both teams are about the same.',
	'Hots Patch Wrong': 'The version is too old.'
  }
}
var bpQueue = [
  {
    action: 'ban',
    team: 0,
    pos: 1,
    heroID: null 
  },
  {
    action: 'ban',
    team: 1,
    pos: 1,
    heroID: null 
  },
  {
    action: 'pick',
    team: 0,
    pos: 1,
    heroID: null 
  },
  {
    action: 'pick',
    team: 1,
    pos: 1,
    heroID: null 
  },
  {
    action: 'pick',
    team: 1,
    pos: 2,
    heroID: null 
  },
  {
    action: 'pick',
    team: 0,
    pos: 2,
    heroID: null 
  },
  {
    action: 'pick',
    team: 0,
    pos: 3,
    heroID: null 
  },
  {
    action: 'ban',
    team: 1,
    pos: 2,
    heroID: null 
  },
  {
    action: 'ban',
    team: 0,
    pos: 2,
    heroID: null 
  },
  {
    action: 'pick',
    team: 1,
    pos: 3,
    heroID: null 
  },
  {
    action: 'pick',
    team: 1,
    pos: 4,
    heroID: null 
  },
  {
    action: 'pick',
    team: 0,
    pos: 4,
    heroID: null 
  },
  {
    action: 'pick',
    team: 0,
    pos: 5,
    heroID: null 
  },
  {
    action: 'pick',
    team: 1,
    pos: 5,
    heroID: null 
  }
]
var tags = { // tag标签名称
  role: [{
	key: 'Warrior',
	color: '#4ca0ff',
    val: 1
  }, {
	key: 'Assassin',
	color: '#ef849b',
    val: 2
  }, {
	key: 'Support',
	color: '#02e9d9',
    val: 3
  }, {
	key: 'Specialist',
	color: '#c06ef9',
    val: 4
  }],
  universe: [{
	key: 'Warcraft',
	color: '#e1c393',
    val: 1
  }, {
	key: 'StarCraft',
	color: '#4ca0ff',
    val: 2
  }, {
	key: 'Diablo',
	color: '#ef849b',
    val: 3
  }, {
	key: 'Retro',
	color: '#4ca0ff',
    val: 4
  }, {
	key: 'Overwatch',
	color: '#ff9900',
    val: 5
  }],
  subclass: [{
	key: 'Tank',
	color: '#ff0099',
    val: 1
  }, {
	key: 'Bruiser',
	color: '#ff0099',
    val: 2
  }, {
	key: 'Ambusher',
	color: '#ff0099',
    val: 3
  }, {
	key: 'Magician',
	color: '#ff0099',
    val: 4
  }, {
	key: 'Shooter',
	color: '#ff0099',
    val: 5
  }, {
	key: 'RangedMixed',
	color: '#ff0099',
    val: 6
  }, {
	key: 'RangedDisturbance',
	color: '#ff0099',
    val: 7
  }, {
	key: 'Healer',
	color: '#ff0099',
    val: 8
  }, {
	key: 'Guardian',
	color: '#ff0099',
    val: 9
  }]
};